### ISSUE TITLE
user not mentioned with reply 

### ISSUE THREAD

**Issue by bartwalczak1** [fmnisme/err-stackstorm#13]
When direct messaging bot on slack it is possible to extract api_user from the execution through 
`{{execution.context.api_user}}`
this field looks like so from the backend:
```u'api_user': u'@bwalczak',```
 
When same message is sent from channel, bot is unable to mention user hence the reply:
```'api_user': u'#botroom/bwalczak',```

**Comment by nzlosh** [comment]
Thanks @bartwalczak1 for reporting this problem.  There may need to be special treatment for strings formatted with `#botroom/user`.  I'll look at how the identification is handled by errbot.

**Comment by nzlosh** [comment]
@bartwalczak1 The patch has been merged so I'll close this ticket.
