### ISSUE TITLE
MESSAGE_SIZE_LIMIT not honoured 

### ISSUE THREAD

**Issue by bartwalczak1** [fmnisme/err-stackstorm#16]
Hi there,
It seems that MESSAGE_SIZE_LIMIT is not honoured for st2 responses. I was able to test it by making an action that returns large output and set MESSAGE_SIZE_LIMIT=100. 
Result was cut in the middle (afaik Slack defaults to 4k characters)

**Comment by nzlosh** [comment]
The plugin doesn't handle `MESSAGE_SIZE_LIMIT`, this is a feature provided directly by errbot.  The plugin calls errbot's method `send_card` when an action aliases has `extra.slack` defined.  `send_card` doesn't implement any chunking for messages that are sent via this method.

At the least, I'll open an issue upstream and if possible I'll provide a fix.

**Comment by bartwalczak1** [comment]
thanks @nzlosh

**Comment by nzlosh** [comment]
Closing issue now the fix for MESSAGE_SIZE_LIMIT has been merged upstream.
