### ISSUE TITLE
Missing step in guide: change post_message.yaml default route

### ISSUE THREAD

**Issue by smonko** [fmnisme/err-stackstorm#23]
Results of st2 commands are not picked from stream untill default route is changed to errbot in 
**packs/chatops/actions/post_message.yaml**

```
...
parameters:
  ...
  route:
    default: "errbot"
...
```

**Comment by nzlosh** [comment]
Thanks for reporting and debugging this problem @Skyneo.  I've updated the documentation to include the required default value for route.
