### ISSUE TITLE
Is this repo under active maintenance?

### ISSUE THREAD

**Issue by vutny** [fmnisme/err-stackstorm#31]
Hi @nzlosh 

I have found out that you started active development and fixing issues in your own repo at https://github.com/nzlosh/err-stackstorm

Just want to check here, would you plan to keep maintaining **this** repository, to port changes, accept issues or contributions and so on?
I'm asking primarily because if I would like to create new bleeding edge StackStorm+Errbot deployment, which plugin is better to pick up?

Thank you for your dedication to this awesome project!

**Comment by nzlosh** [comment]
With the addition of OOB authentication and bumping to v2.0, it seemed like the right moment to move development to my own account for better control over the repository.  It'll allow me to add collaborators and integrations in the future, which I'm not able to do here.

**Comment by vutny** [comment]
Great. Then, maybe it would be worth to add some bold text at the top of README file mentioning this repo has been abandoned in favor of yours, or something like that.

If original author @fmnisme would wish, he could archive the repo sometime in the future.

**Comment by nzlosh** [comment]
Yes, I was planning to do something along those lines, I'll add it now.  BTW nice articles on medium.

**Comment by vutny** [comment]
Thanks! I'm very glad you like them.
