### ISSUE TITLE
Possibility of adding threading?

### ISSUE THREAD

**Issue by moet78** [fmnisme/err-stackstorm#33]
Similar to the issue in https://github.com/StackStorm/hubot-stackstorm/issues/161. They have not deliver a solution yet.. 

I wonder if err-stackstorm could provide a threading in slack solution?

**Comment by nzlosh** [comment]
**FYI - This repository is no longer used for active development of the err-stackstorm plugin. The active repository is https://github.com/nzlosh/err-stackstorm**.

This sounds like a good feature and a PR would be most welcome against the active repository.
